import './globals.css';
import { gql } from '@apollo/client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getClient } from '../util/apolloClient';
import { LogoutButton } from './(auth)/logout/LogoutButton';
import { ApolloClientProvider } from './ApolloClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const fakeSessionToken = cookies().get('fakeSession');
  const { data } = await getClient().query({
    query: gql`
      query LoggedInUser($firstName: String!) {
        loggedInUser(firstName: $firstName) {
          id
          firstName
          age
        }
      }
    `,
    variables: {
      firstName: fakeSessionToken?.value || '',
    },
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: '100%',
            backgroundColor: 'lightblue',
            padding: '1rem',
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <div
            style={{
              display: 'flex',
              gap: '10px',
            }}
          >
            <Link href="/">Home</Link>
            <Link href="/animals">Animals</Link>
            <Link href="/animals/admin">Animal admin</Link>
          </div>

          <span>{data.loggedInUser?.firstName}</span>
          {data.loggedInUser?.firstName ? (
            <LogoutButton />
          ) : (
            <Link href="/login">Login</Link>
          )}
        </nav>
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
